version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    container_name: 'olecram-rabbit'
    ports:
        - 5682:5672
        - 15682:15672
    volumes:
        - e:/volumens/rabbitmq/data/:/var/lib/rabbitmq/
        - e:/volumens/rabbitmq/log/:/var/log/rabbitmq/

    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge


