apiVersion: apps/v1
kind: Deployment
metadata:
  name: olecram-daemon-1
  labels:
    app: olecram-daemon-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olecram-daemon-1
  template:
    metadata:
      labels:
        app: olecram-daemon-1
    spec:
      containers:
      - name: olecram-daemon-1-cont
        image: moviedomfo/olecram-daemon:2.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: logs1-volume
          mountPath: /app/logs
        env:
        - name: NODE_ENV
          value: "production"
        - name: APP_FILES
          value: "/app/logs"
      volumes:
      - name: logs1-volume
        persistentVolumeClaim:
          claimName: logs1-pvc
