apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: logs1-pv  # Vincula explícitamente al PV logs1-pv
  storageClassName: manual  
