# Etapa 1: Construcción
FROM node:18 AS builder

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar archivos necesarios para la construcción
COPY package*.json ./
COPY yarn.lock ./
COPY tsconfig.json ./
COPY esbuild.config.js ./
COPY src ./src

# Instalar dependencias necesarias para producción 
RUN yarn install && \
    yarn builddocker

# Etapa 2: Imagen de Producción
FROM node:18-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los artefactos generados por la etapa de construcción
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package*.json ./

CMD ["node", "dist/app.js"]