apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapi-api-dep
  labels:
    app: rapi-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapi-api
  template:
    metadata:
      labels:
        app: rapi-api
    spec:
      containers:
      - name: rapi-api-cont
        image: moviedomfo/rapi-api:2.1
        ports:
        - containerPort: 80
